# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
permalink: /:title

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		      "Now"
description:	      "What I'm currently working on"
author:              "Lee Tusman"


baseurl: "/now" # the subpath of your site, e.g. /blog
url: "http://leetusman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 2sman2sman
github_username:  lee2sman
